# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: employee.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65mployee.proto\x12\x11tutorial.employee\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n\x0eMessageRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1f\n\x0fMessageResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"`\n\x17\x45mployeeCreationRequest\x12\x11\n\tfirstName\x18\x01 \x01(\t\x12\x10\n\x08lastName\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\x10\n\x08\x62irthday\x18\x04 \x01(\t\"&\n\x18\x45mployeeCreationResponse\x12\n\n\x02id\x18\x01 \x01(\x05\" \n\x11MedianAgeResponse\x12\x0b\n\x03\x41ge\x18\x01 \x01(\x05\x32\x9f\x04\n\x0c\x45mployeeStub\x12T\n\x0bSendMessage\x12!.tutorial.employee.MessageRequest\x1a\".tutorial.employee.MessageResponse\x12\x66\n\x0b\x41\x64\x64\x45mployee\x12*.tutorial.employee.EmployeeCreationRequest\x1a+.tutorial.employee.EmployeeCreationResponse\x12{\n%CreateEmployeeAsStreamAndGetMedianAge\x12*.tutorial.employee.EmployeeCreationRequest\x1a$.tutorial.employee.MedianAgeResponse(\x01\x12\x85\x01\n-CreateEmployeeAsStreamAndGetMedianAgeAsStream\x12*.tutorial.employee.EmployeeCreationRequest\x1a$.tutorial.employee.MedianAgeResponse(\x01\x30\x01\x12L\n\x0cGetMedianAge\x12\x16.google.protobuf.Empty\x1a$.tutorial.employee.MedianAgeResponseB\x0f\xaa\x02\x0c\x45mployeeGrpcb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'employee_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\014EmployeeGrpc'
  _MESSAGEREQUEST._serialized_start=66
  _MESSAGEREQUEST._serialized_end=96
  _MESSAGERESPONSE._serialized_start=98
  _MESSAGERESPONSE._serialized_end=129
  _EMPLOYEECREATIONREQUEST._serialized_start=131
  _EMPLOYEECREATIONREQUEST._serialized_end=227
  _EMPLOYEECREATIONRESPONSE._serialized_start=229
  _EMPLOYEECREATIONRESPONSE._serialized_end=267
  _MEDIANAGERESPONSE._serialized_start=269
  _MEDIANAGERESPONSE._serialized_end=301
  _EMPLOYEESTUB._serialized_start=304
  _EMPLOYEESTUB._serialized_end=847
# @@protoc_insertion_point(module_scope)
